language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

services:
  - mongodb

install:
  - "pip install coverage"
  - "pip install nose"
  - "pip install coveralls"
  - "pip install -e .[testing]"

script: "nosetests -v --with-coverage --cover-package=sprox --cover-erase"

after_success:
  coveralls
