language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

services:
  - mongodb

install:
  - "pip install coverage"
  - "pip install nose"
  - "pip install coveralls"
  - "pip install -e .[testing]"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -e .[testing-mongodb]; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -e .[testing-mongodb]; fi

script: "nosetests -v --with-coverage --cover-package=sprox --cover-erase"

after_success:
  coveralls
